name: Enforce read-only repo status

on:
  issues:
    types: opened
  pull_request_target:
    types: opened

jobs:
  lockdown:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          github-token: ${{ github.token }}
          issue-comment: |
            This is a read-only mirror.

            Issues should be filed at https://github.com/itcig/itcig/issues. Be sure to mention the product that the issue is regarding.
          skip-closed-issue-comment: true
          pr-comment: |
            This is a read-only mirror.

            Pull requests should be made against the monorepo at https://github.com/itcig/itcig.
          skip-closed-pr-comment: true
